### ISSUE TITLE
Does contiv support kubernetes v1.6?

### ISSUE THREAD

**Issue by feiskyer** [contiv/netplugin#834]
There is same question at https://github.com/kubernetes/kubernetes.github.io/issues/2942#issuecomment-288208514, but no response is got there.

**Comment by opsnull** [comment]
same question here.

**Comment by neelimamukiri** [comment]
Contiv supports it, if you install it on the host as a systemd service (https://github.com/contiv/demo/tree/master/k8s). Current kubectl based installation is not supported due to https://github.com/kubernetes/kubernetes/issues/44041. We will be testing it once the fix is available in 1.6.2.

**Comment by opsnull** [comment]
I installed kubernetes 1.6.2, but test failed:

```
$ kubectl get pods -n kube-system -o wide|grep contiv
contiv-api-proxy-rqpbp                  1/1       Running   0          3m        10.64.3.7      10.64.3.7
contiv-netmaster-h8j0f                  1/1       Running   0          3m        10.64.3.7      10.64.3.7
contiv-netplugin-33s6n                  1/1       Running   0          3m        10.64.3.7      10.64.3.7
```

kubectl describe pod defaultnet-busybox1
`  13s           0s              12      kubelet, 10.64.3.7                      Warning         FailedSync      Error syncing pod, skipping: failed to "CreatePodSandbox" for "defaultnet-busybox1_default(624cd92d-2657-11e7-af4a-8cdcd4b3be48)" with CreatePodSandboxError: "CreatePodSandbox for pod \"defaultnet-busybox1_default(624cd92d-2657-11e7-af4a-8cdcd4b3be48)\" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod \"defaultnet-busybox1_default\" network: Contiv:Error getting labels; Err: 401 Unauthorized"`

```
$ grep 401 /var/log/contivk8s.log |tail -1
time="2017-04-21T14:00:59+08:00" level=info msg="cniErr: {"cniVersion":"0.1.0","code":1,"msg":"Contiv:Error getting labels","details":"Err: 401 Unauthorized"}" NETNS=28976

```

but I already used cluster-admin ClusterRole:
```

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: contiv-netplugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: contiv-netplugin
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contiv-netplugin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: contiv-netmaster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: contiv-netmaster
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contiv-netmaster
  namespace: kube-system

---
```
